export const TIP_VISIBLE_MS = 60000;
export const TIP_REPLACE_COOLDOWN_MS = 5000;
export const VISUAL_DUPLICATE_WINDOW_MS = 900;
export const PROCESS_TRANSCRIPT_TIMEOUT_MS = 10000;

export const POSITION_STABILITY_FRAMES = 3;
export const OPENING_HISTORY_MAX_PLIES = 12;
export const PLAUSIBILITY_REJECT_LIMIT = 5;
export const OSCILLATION_REPEAT_LIMIT = 1;
